version: "3.2"
services:
  app:
    image: node:8.15.0-alpine
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm start
